add diagram and dfu overview introduction
golioth/docs pull request #123
Opened 2021-12-15 15:27 UTC by vancefarren

2021-12-17 17:11 UTC, vitprajzler requested changes

2021-12-17 17:11 UTC, vitprajzler commented on docs/firmware/device-sdk/firmware-upgrade/overview-dfu.md
> +The DFU sample demonstrates the capability of the Golioth DFU service from the perspective of the device.  The following diagram illustrates the architecture of the sample within the Device SDK archi
Can you please add the link to the sample repo?

2021-12-17 19:46 UTC, vitprajzler approved these changes

2021-12-20 12:26 UTC, mniestroj approved these changes

2022-01-07 22:45 UTC, merged