docs: add docs for the InfluxDB outputstream
golioth/docs pull request #267
Opened 2023-07-21 19:25 UTC by tim-golioth

2023-07-21 19:44 UTC, dylanswartz commented
Heads up @ChrisGammell @szczys we want to hold off merging these until we remove the feature flag in production hiding this feature.

2023-07-21 19:47 UTC, dylanswartz reviewed
Great work!

2023-07-21 19:50 UTC, szczys commented
@dylanswartz okay, it would be good to set it as a draft PR until then.

2023-07-21 20:40 UTC, tim-golioth commented
converted this a draft PR for the time being.

2023-07-26 16:01 UTC, szczys requested changes
In addition to the inline comments I left, please wrap lines at 80 columns where possible. Thanks!

2023-07-31 14:57 UTC, tim-golioth commented on docs/cloud/2-output-streams/8-influx/README.md
> +```
this is json, not yaml.

2023-07-31 14:57 UTC, tim-golioth commented on docs/cloud/2-output-streams/8-influx/README.md
> +```
this is the InfluxDB line protocol, so it's neither yaml nor json.

2023-07-31 14:59 UTC, tim-golioth commented on docs/cloud/2-output-streams/8-influx/assets/2023-07-20_15-37.png
this file isn't even used. removed.

2023-07-31 18:35 UTC, tim-golioth commented
> > This and any other style requirements should be documented somewhere, if they aren't already.
> 
> Good idea! I [added an .editorconfig file for this setting](https://github.com/golioth/docs/pull/271) when I originally left that comment, and have just opened another PR to [add styling info to the README](https://github.com/golioth/docs/pull/272).

TIL! i didn't know neovim supports [editorconfig](http://neovim.io/doc/user/editorconfig.html).

2023-07-31 18:36 UTC, tim-golioth commented
@szczys i made a couple minor cleanup changes after you approved. would you please take another look when it's convenient?

2023-07-31 20:57 UTC, szczys commented
> @szczys i made a couple minor cleanup changes after you approved. would you please take another look when it's convenient?

Still LGTM!

2023-08-15 20:00 UTC, dylanswartz requested changes

2023-08-15 20:00 UTC, dylanswartz commented on docs/cloud/2-output-streams/8-influx/README.md
> +slug: /cloud/output-streams/influx
```suggestion
slug: /cloud/output-streams/influxdb
```

2023-08-15 23:40 UTC, dylanswartz approved these changes

2023-08-15 23:44 UTC, merged